// src/components/Console/Console.svelte
<div class="bg-gray-900 text-white rounded-lg p-4 font-mono text-sm">
  <div 
    bind:this={containerRef}
    class="max-h-[500px] overflow-y-auto"
  >
    {#each $messages as message}
      <ConsoleMessage {message} />
    {/each}
  </div>
</div>

<script lang="ts">
  import { onMount } from 'svelte';
  import ConsoleMessage from './ConsoleMessage.svelte';
  import type { Message } from '../../types/console';
  
  export let messages: Message[];
  let containerRef: HTMLDivElement;

  $: if (containerRef && messages) {
    containerRef.scrollTop = containerRef.scrollHeight;
  }
</script>

// src/components/Console/Console.tsx
import React, { useEffect, useRef } from 'react';
import { ConsoleMessage } from './ConsoleMessage';
import { useConsoleStore } from '../../stores/consoleStore';
import { useAutoScroll } from '../../hooks/useAutoScroll';

export function Console() {
  const containerRef = useRef<HTMLDivElement>(null);
  const messages = useConsoleStore(state => state.messages);
  
  useAutoScroll(containerRef, messages);

  return (
    <div className="bg-gray-900 text-white rounded-lg p-4 font-mono text-sm">
      <div 
        ref={containerRef}
        className="max-h-[500px] overflow-y-auto"
      >
        {messages.map((message, index) => (
          <ConsoleMessage 
            key={index}
            message={message}
          />
        ))}
      </div>
    </div>
  );
}
